signitmain/flask_blog/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

signitmain/flask_blog/flaskblog/main/routes.py
from flask import render_template, request, Blueprint,url_for
from flaskblog.models import Post

main = Blueprint('main', __name__)
@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html',posts=posts)
@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html',title='home')
@main.route("/interpreter")
def interpreter():
    return render_template('interpreter.html',title='interpreter')










# @main.route("/contact us")
# def contactus():
#     return render_template('contactus.html',title='contactus')
# @main.route("/bonus")
# @login_required
# def bonus():
    
#     return render_template('bonus.html',title='bonus')

# @main.route("/")
# def index():
#  random_bird = BirdDetails.query.order_by(func.random()).first()
#  return render_template('main/index.html', bird = random_bird)
# from birdnet.models import User, Thread, Reply, BirdDetails, db

signitmain/flask_blog/flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.blog'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

signitmain/flask_blog/flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

signitmain/flask_blog/flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}<main role="main" class="container account">
    <div id="account">

        <div class="container">
            <div id="account-row" class="row justify-content-center align-items-center">
                <div id="account-column" class="col-md-6">
                    <div id="account-box" class="col-md-12">
                        <form id="account-form" class="form" action="" method="post">


                            <div class="media">
                                <img class="rounded-circle account-img" src="{{ image_file }}">
                                <div class="media-body">
                                    <h2 class="account-heading">{{ current_user.username }}</h2>
                                    <p class="text-secondary">{{ current_user.email }}</p>
                                </div>
                            </div>


                            <form method="POST" action="" enctype="multipart/form-data">
                                {{ form.hidden_tag() }}
                                <fieldset class="form-group">
                                    <legend class="border-bottom mb-4">Account Info</legend>
                                    <div class="form-group">
                                        {{ form.username.label(class="form-control-label") }}

                                        {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.username.errors %}
                                            <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {{ form.email.label(class="form-control-label") }}
                                        {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {{ form.picture.label() }}
                                        {{ form.picture(class="form-control-file") }}
                                        {% if form.picture.errors %}
                                        {% for error in form.picture.errors %}
                                        <span class="text-danger">{{ error }}</span></br>
                                        {% endfor %}
                                        {% endif %}
                                    </div>
                                </fieldset>
                                <div class="form-group text-center">
                                    {{ form.submit(class="btn1 signit") }}
                                </div>
                            </form>



</main>
{% endblock content %}

signitmain/flask_blog/flaskblog/templates/blog.html
{% extends "layout.html" %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    
    {% if current_user.is_authenticated %}
<div class="col-md-4" >
  <div class="content-section">
    <h3>blog</h3>
    
      <ul class="list-group">
        <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}"> Create New Post</a></li>
        
        
       
      </ul>
    </p>
  </div></div>{% endif %}
  
   
  <div class="col-md-8">
    
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn colored-section mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn signit mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}</div>
{% endblock content %}

signitmain/flask_blog/flaskblog/templates/home.html
{% extends "layout.html"%}
{% block content%}

<section id="features" class="colored-section ">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6 ">
          <h1 class="big-heading"><strong> Personalised Sign Language Interpreter</strong></h1>
          <p>View the Sign Chart Now!</p>
          
          <a href="{{url_for('static',filename = 'assets/sign.png')}}"><button type="button" class="btn btn-outline-light btn-lg ">Click Here!</button></a>
      </div>

      
        <div class="col-lg-6 carousel">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="{{url_for('static',filename = 'assets/6.png')}}" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{{url_for('static',filename = 'assets/7.png')}}" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{{url_for('static',filename = 'assets/8.png')}}" alt="Third slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{{url_for('static',filename = 'assets/9.png')}}" alt="Third slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{{url_for('static',filename = 'assets/10.png')}}" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev " href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span  aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span  aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>     
                 
                
      
  </div>
</div>
</section>
<section id="features" class="grey-section">
  <div class="container-fluid">
      <div class="row">
          <div class="col-lg-12 feature-desc">
              
              <h1 class="font-bold">About us</h1>
              
              <p id="p1">SignIt is a platform for all the signers to interpret and interact.
                With our  interpreter feature, the sign language students and learners, interpreters can learn, practice and interpret sign language. The blog feature will enable you all to express your thoughts about sign language and share knowledge regarding the same! So what are you waiting for? Signup Now!!</p>
          </div>
         
</section>


<section id="features" class="white-section">
        <div class="container-fluid">
          <h1 class="font-bold text-center">Our Features</h1>
            <div class="row">
                <div class="col-lg-6 feature-desc">
                  
                    <i class="fas fa-check-circle icon"></i>
                    <h3 class="title-icon"><a href="{{ url_for('main.interpreter') }}">Interpreter</a></h3>
                    
                </div>
                <div class="col-lg-6 feature-desc">
                    <i class="fas fa-bullseye icon"></i>
                    <h3 class="title-icon"><a href="{{ url_for('main.blog') }}">blog</a></h3>
                    
                </div>
               
            </div>
        </div>
    </section>
<section id="features" class="grey-section">
        <div class="container-fluid">
          <h1 class="font-bold text-center">Sign Interpreter</h1>
            <div class="row">
                <div class="col-lg-6 feature-desc">
                  
                  <section id="features" >
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-3 feature-desc">
                              <image src="{{url_for('static',filename = 'assets/11.png')}}" alt="sry" class="title-image"></image>
                                
                                
                               
                            </div>
                            <div class="col-lg-9 feature-desc">
                                
                                
                                
                                <p id="p1">try signit's indian sign language interpreter for free- alphabets version</p>
                                <a class="btn colored-section" href="#">click here to start  alphabets section</a>
                            </div>
                           
                            
                        </div>
                    </div>
                </section>
                    
                </div>
                <div class="col-lg-6 feature-desc">
                  <section id="features" >
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-4 feature-desc">
                              <image src="{{url_for('static',filename = 'assets/14.png')}}" alt="sry" class="title-image"></image>
                                
                            
                                
                            </div>
                            <div class="col-lg-8 feature-desc">
                                
                                
                                
                                <p id="p1">try indian sign language interpreter for free <strong>after login</strong>- words version
                                    {% if current_user.is_authenticated %}<a class="btn colored-section" href="#">click here to start  word section</a>
                                    {% else %}
                                    <a class="btn colored-section" href="{{ url_for('users.login') }}">click here to start  word section</a>
                                    {% endif %}
                            </div>
                           
                            
                        </div>
                    </div>
                </section>
            
            
                    
                </div>
               
            </div>
        </div>
    </section>
                

   

 


   
    <footer  class="white-section">
            
      <center><p>© Copyright by Signit</p></center> 
      <center><a href="#">signit@gmail.com</a>|| <a href="#">privacy policy</a></center> 
      

   </footer>
    






{%endblock content%}

signitmain/flask_blog/flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
     
     <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;900&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/1c9ad4b785.js" crossorigin="anonymous"></script>

    {% if title %}
        <title>signit- {{ title }}</title>
    {% else %}
        <title>signit</title>
    {% endif %}
</head>
<body>
  
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark colored-section fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/"><image class="steel" src="{{url_for('static',filename = 'assets/logo.png')}}" alt="sry" class="title-image" height="60px" width="70px"></image>Signit</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Blog</a>
              <a class="nav-item nav-link" href="{{ url_for('main.interpreter') }}">Interpreter</a>
              
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
   
          
            <div class="row">
              <div class="col">
                {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                    {% for category, message in messages %}
                      <div class="alert alert-{{ category }}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
              </div>
              
            </div>
       
          
         
    
    


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

signitmain/flask_blog/flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %} <main role="main" class="container " >
    <div id="login">
        
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            
        
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-sm is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group ">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group text-center">
                {{ form.submit(class="btn1 signit") }}
            </div>
            <small class="text-muted ml-2 ">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3 text-center">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div></div></div></div></div></main>
{% endblock content %}

signitmain/flask_blog/flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}


  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        
        {% else %}
        <div>
          <a class="btn colored-section btn-sm mt-1 mb-1" href="{{ url_for('users.login')}}">login to edit</a>
          
        </div>

        
        {% endif %} 
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
 

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

signitmain/flask_blog/flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn colored-section mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn signit mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}